# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/erikstmartin/go-testdb
%global goipath         github.com/erikstmartin/go-testdb
%global commit          8d10e4a1bae52cd8b81ffdec3445890d6dccab3d

%gometa

%global common_description %{expand:
Framework for stubbing responses from go's driver.Driver interface.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Framework for stubbing responses from go's driver.Driver interface

# Upstream license specification: BSD-2-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Sep 05 2021 Petr Menšík <pemensik@redhat.com> - 0-0.1%{?dist}.20210905git8d10e4a
- Initial package

